### ISSUE TITLE
fatal error while clone

### ISSUE THREAD

**Issue by yatinmob** [bagisto/bagisto-docker#1]
git clone https://wkrepo.webkul.com/laravel/bagisto-docker-compose.git
Cloning into 'bagisto-docker-compose'...
fatal: unable to access 'https://wkrepo.webkul.com/laravel/bagisto-docker-compose.git/': Failed to connect to wkrepo.webkul.com port 443: Operation timed out

**Comment by vaishaliwebkul** [comment]
Hi @yatinmob 
Instead of cloning the project https://wkrepo.webkul.com/laravel/bagisto-docker-compose.git
you can manually create docker-compose.yml as mention in the doc.

Thanks.
