### ISSUE TITLE
Is the version of Bagisto used in bagisto-docker the same as the latest version of the "official" repo?

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [bagisto/bagisto-docker#15]
Hi,

I would want to contribute to https://github.com/bagisto/bagisto but using Docker for installation.
In order to contribute to Bagisto, I need to pull the latest release. If I use this Docker containairization repo, will I have the latest version of Bagisto please?

Thank you.
best regards,

**Comment by devansh-webkul** [comment]
Currently, there is one command which is resetting the version of Bagisto to the latest one. You can remove the command to use the master one if you want,
https://github.com/bagisto/bagisto-docker/blob/e667f7bdc74b7840768a8d65b14543af8b93291e/setup.sh#L29

The remaining steps are the same for the installation.
