### ISSUE TITLE
useradd: user 'root' already exists when running setup.sh

### ISSUE THREAD

**Issue by prestonzen** [bagisto/bagisto-docker#19]
useradd: user 'root' already exists happens when I try to run it

![image](https://github.com/bagisto/bagisto-docker/assets/36439263/a1102bdc-2d72-4982-9bf4-9723dbd6291d)

**Comment by archtheonly** [comment]
hello!
run the script without sudo, that should help.

**Comment by devansh-webkul** [comment]
Not able to reproduce this, can you do a fresh setup.
