### ISSUE TITLE
Version PHP 7.3 is necesary

### ISSUE THREAD

**Issue by yickson** [bagisto/bagisto-docker#3]
`docker exec -i apache2 bash -c "su - www-data -s /bin/bash -c 'composer create-project bagisto/bagisto'"
Installing bagisto/bagisto (v1.2.0)
  - Installing bagisto/bagisto (v1.2.0): Downloading (100%)         

  Problem 1
    - Installation request for mockery/mockery 1.4.0 -> satisfiable by mockery/mockery[1.4.0].
    - mockery/mockery 1.4.0 requires php ^7.3.0 -> your PHP version (7.2.15) does not satisfy that requirement.
`

**Comment by vaishaliwebkul** [comment]
Hi @yickson 
php 7.3 is required for bagisto v1.2.0 or higher so kindly enable it then try again.

**Comment by LabN36** [comment]
@prashant-webkul i believe atleast php 7.3 is required in order to run this project. do you guys accept pull request for this repository ?

https://github.com/bagisto/bagisto-docker/blob/7d959ff2347dd450c528d7fae44e6070eae56c39/docker-compose.yml#L6
