### ISSUE TITLE
Dockerfile & Docker-compose

### ISSUE THREAD

**Issue by rayrizqie** [bagisto/bagisto-docker#4]
hi i already have nginx for my webserver
can you provide me Dockerfile and docker-compose file with php-fpm image?

i alr try it with my dockerfile

```
FROM php:7.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \ 
    libzip-dev \ 
    libmagickwand-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install imagick \ 
    && docker-php-ext-enable imagick

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd intl mysqli

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www
```
and got error 
![image](https://user-images.githubusercontent.com/34916137/94546393-05b4d400-0278-11eb-843d-dc25802c9b27.png)

**Comment by devansh-webkul** [comment]
Well, currently we have Dockerfile and compose file for apache only. From your error, it looks like some environment variables are missing.

**Comment by rgalaz** [comment]
I'm having the same error, any solution?
