### ISSUE TITLE
Why app/public_html and not app/public?

### ISSUE THREAD

**Issue by pabloelcolombiano** [bagisto/bagisto-docker#6]
Hi there,

first thanks for the great job you guys are doing!

I just installed the bagisto docker, and everything went really well, until I called localhost:8000.
Two days long I read about apache, learned lots of interesting stuff, but nothing worked. Until I realized, reading thoroughly the Readme of the present repository, that the public folder in not app/public, as Laravel conventions suggest, but app/public_html.

It is definitely my bad, not to have read the Readme in detail. Assuming that everything followed the Laravel convention, the public folder name is the least I would have expected to fail.

Thus, my question: why `app/public_html` and not `app/public`?

**Comment by devansh-webkul** [comment]
Hi @pabloelcolombiano,

It depends on the settings, your point of view is right.

Actually it's an `app/public`, we just created a symbolic link.

**Comment by alpondith** [comment]
I followed installing Bagisto using Docker Installation process according to the  [documentation](https://devdocs.bagisto.com/1.x/introduction/docker.html#introduction). After creating symlink what i figured out that `http://localhost`  doesn't load the website where as` http://localhost/public_html/` was loading the website properly. For the solution i just created  `.htacess`  file inside app folder which is  `app/.htaccess` (Caution : not to the `app/bagisto/public/.htacess`) . 

Inside the `.htacess` file added below lines and this worked as i expected. 

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^(.*)$ public_html/$1 [L]
</IfModule>
```
